### ISSUE TITLE
Error RuntimeWarning: Invalid value encountered in median   r = func(a, **kwargs)

### ISSUE THREAD

**Issue by aichilizi** [Weeks-UNC/Superfold#1]
Hi,

After I ran the script, I didn't get plot which shows shannon entropy, Shape reactivity and arcplot in parallel.
The bottom of the log file says python2.7/site-packages/numpy/lib/function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)"

I set the partition window size to either 1000 or 1500 and kept the other parameters as default. My RNA is around 10K bp.
Do you know what the problem is?

Thanks!!

**Comment by twchrist** [comment]
Hi,

Your parameters sound fine, also I don't think the RuntimeWarning is the source of your issue.

It could be a number of things, I want to check the basics first. Have you run Superfold successfully before? Are you sure your map file is in the correct format? Do other python scripts successfully generate figures? If you are using a server, can you display figures?

If the answer to all of those is yes, please attach your map file and we'll try to troubleshoot on our end.

**Comment by aichilizi** [comment]
Hi, Thanks so much for your immediate response.
1. I used ShapeMapper generated map file. 
2. This is my first time running SuperFold and I can get shannon entropy and arcplot figure individually but not the integrated figure comparing shannon entropy, Shape reactivity and arcplot in parallel.
3. I am using Linux terminal server.
4. I have run the map file of TPP example from ShapeMapper2 and I got the same result.

**Comment by twchrist** [comment]
Thanks for all of the details. So some of the issues have been addressed. Superfold was not designed to display the arcplot with the SHAPE/Shannon data in the same figure. Generally that is something you have to do manually with the two separate plots. 

As for the issue with SHAPE data not plotting at all, that has now been fixed. Download the new V1.1 update of Superfold and SHAPE/Shannon data will display on the same plot.
