### ISSUE TITLE
Pseudoknots in Superfold prediction

### ISSUE THREAD

**Issue by angelika888** [Weeks-UNC/Superfold#10]
Hello!

I'd like to ask if Superfold is able to predict pseudoknots?
I thought that a separate Shapeknots calculation is needed before the Superfold prediction
and last I performed only Superfold calculation and in the final model, there are 2 pseudoknots.

I will be grateful for advise.

Regards,
Angelika

**Comment by Psirving** [comment]
Hi again! I'm not sure if anyone else is likely to respond here, but I have a loose theory on how Superfold might produce a structure model with pseudoknots. Superfold is an implementation of the `fold` program from RNAStructure. `fold` does not predict pseudoknots. However, Superfold uses `fold` on sliding windows, then has an algorithm to combine these windows into a single structure. If different windows predict non-nested, non-conflicting helices, they might be combined to make a pseudoknotted structure. I'm not sure this is a validated method for predicting pseudoknots, and it is fundamentally different from how ShapeKnots works.

![superfold](https://user-images.githubusercontent.com/1638005/227969798-a3e85e95-aaaf-4560-8631-5693eb74d322.jpg)

**Comment by angelika888** [comment]
Hi!
Thank you for your answer. Unfortunately, the predicted pseudoknotted helices are conflicting. The end of the first interaction is interspersed with the beginning of the other one and the third interaction between, like ((...)[)[..<<..]]..>> , so one of these interactions is the false one. 
I wonder how sure the predictions of PK at Superfold are (is it only a bug of the program?).
