### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by gunjangunjan22** [Weeks-UNC/Superfold#11]
I am trying to install Superfold in my Linux based system, but i got issue with fold, partition function and probability plot. It says the above mentioned exe are not in path, but i already changed my ./~ bashprofile. I tried to reinstall everything, but still it doesn't work. 
Could you please look into this issue? Thank you in advance.

**Comment by Psirving** [comment]
To help you with this, I'll need more information. Please follow these steps:

1. Verify that the RNAstructure executables are on your PATH:  type `partition --help`
2. If that doesn't work, verify that your path includes your RNAstructure installation: `echo -e ${PATH//:/\\n}`
3. If RNAstructure is on your PATH but `partition --help` doesn't work, you need to build RNAstructure.
4. If this all works, but Superfold still says it can't find fold, partition, and probabilityplot, reply here with the entire error message you're seeing with superfold.py.

**Comment by gunjangunjan22** [comment]
Hi
I am trying to add RNAstructure installation on path in ~/.bash_profile
 export PATH=$PATH:$home/gunjan/Desktop/Biotools/superfold/Superfold-master/RNAstructure/exe
export PATH=$PATH:$home/gunjan/Desktop/Biotools/superfold/Superfold-master/RNAstructure/data_tables

but it is not working. I checked my path it shows 
/home/gunjan/miniconda3/envs/py2/bin
/home/gunjan/miniconda3/condabin
/home/gunjan/.local/bin
/home/gunjan/bin
/opt/ultrascan3/bin
/opt/pymol
/usr/share/Modules/bin
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/usr/local/cuda/bin
and error is still same.

**Comment by Psirving** [comment]
Try this:
```bash
source ~/.bash_profile
echo -e ${PATH//:/\\n}
```

If this adds RNAstructure to PATH: try logging out and back in and see if your PATH is still correct.

**Comment by gunjangunjan22** [comment]
Yeah It works now. i have a follow up question, do i have to edit bash-profile every time i use. because when i logged out and checked my path, it didn't show anything. After running the command mentioned above, it worked.

**Comment by Psirving** [comment]
Typically, when bash starts an interactive login shell, it looks for ~/.bash_profile and loads it. This isn't the case for your environment setup, and I don't have any insight as to why that is. You could try .bashrc or .profile instead.

**Comment by gunjangunjan22** [comment]
Okay. Thank you
