### ISSUE TITLE
Superfold crashed on partition function calculation

### ISSUE THREAD

**Issue by sreisser** [Weeks-UNC/Superfold#2]
Hi,

I get the following error when I run Superfold with the sample input file 16S.1m7.map.txt. It worked in an older version.

Could you please have a look?

Cheers
Sabine

$ python2 Superfold.py 16S.1m7.map.txt 
results_16S.1m7.map.txt_867e
log file location: results_16S.1m7.map.txt_867e/log_results_16S.1m7.map.txt_867e.txt

starting Partition function calculation...
Traceback (most recent call last):
  File "Superfold.py", line 1421, in <module>
    main()
  File "Superfold.py", line 159, in main
    partitionPairing = generateAndRunPartition(args.mapObj, args.allConstraints,args.partitionWindowSize, args.partitionStepSize, args.safeName, args.SHAPEslope, args.SHAPEintercept, args.np, args.maxPairingDist)
  File "Superfold.py", line 537, in generateAndRunPartition
    dpObject = mainAssemble(dirname,trim=300)
  File "Superfold.py", line 875, in mainAssemble
    firstDP = min([i[0] for i in targetDP.keys()])
ValueError: min() arg is an empty sequence

**Comment by twchrist** [comment]
This error occurs when the binaries for RNAStructure have not been built. See https://rna.urmc.rochester.edu/Text/Building.html for instructions on how to build the binaries. 

You can check to make sure the binaries have been built correctly by running any of the executables in RNAStructure. If they run without error then Superfold should run too.
