### ISSUE TITLE
.mapd file creating - Error

### ISSUE THREAD

**Issue by angelika888** [Weeks-UNC/Superfold#5]
Hi,
My operating system is Linux Ubuntu. I've been trying to convert my NMIA.map and 1M6.map files (Shapemapper2 output files) to .mapd file using differenceByWindowSHAPEMAP.py code.
But I get the message as below:

```
angelika@angelika-VirtualBox:~/Superfold-master$ python differenceByWindowSHAPEMAP.py NMIA.map 1M6.map nmia-1m6.mapd 25
Traceback (most recent call last):
  File "differenceByWindowSHAPEMAP.py", line 392, in <module>
    dReport00,dReport11=scaleSampleReactReport(dReport0,dReport1,isScale=True,window=int(sys.argv[4]))
  File "differenceByWindowSHAPEMAP.py", line 335, in scaleSampleReactReport
    aScale=scaleShapeDataWindow(dReport0['normDiff'],dReport1['normDiff'],deg=window)
  File "differenceByWindowSHAPEMAP.py", line 230, in scaleShapeDataWindow
    fittedSig=fitLinear(aX,aY,len(data1))
  File "differenceByWindowSHAPEMAP.py", line 184, in fitLinear
    fittedData[0:x[0]]=y[0]
TypeError: slice indices must be integers or None or have an __index__ method

```
I will be thankful if you will take a look on this problem.

Regards,
Angelika

**Comment by twchrist** [comment]
There was just an issue in the code with integer casting that occurs for some python 2 versions. It has been addressed and should work for any python 2 version.

**Comment by angelika888** [comment]
Thank you! Indeed, there was a problem with Python version. Now, I can get output .mapd file, but there appears additional message:

`angelika@angelika-VirtualBox:~/Superfold-master$ python differenceByWindowSHAPEMAP.py NMIA.map 1M6.map TEST.mapd 25

differenceByWindowSHAPEMAP.py:412: RuntimeWarning: divide by zero encountered in divide
  diffReport['zfactor'] = 1- (3*(dReport00['normDiffErr']+dReport11['normDiffErr']))/(np.absolute(diffReport['normDiff']))

differenceByWindowSHAPEMAP.py:412: RuntimeWarning: invalid value encountered in divide
  diffReport['zfactor'] = 1- (3*(dReport00['normDiffErr']+dReport11['normDiffErr']))/(np.absolute(diffReport['normDiff']))
`

In .mapd file in positions with differential SHAPE reactivity '0.0', there for Z-factor is '-inf'. Is it ok?
