### ISSUE TITLE
Program Fold not found in the path

### ISSUE THREAD

**Issue by eumhh** [Weeks-UNC/Superfold#8]
When I try to run Syperfold, I get the messages below and there is no output.

> python ~/Superfold.py test.map
```
Program Fold not found in the path
Program partition not found in the path
Program ProbabilityPlot not found in the path
...exiting
```

I'm working on the environment for python 2.7 using anaconda 4.12.0 on Ubuntu 20.04.
Actually it worked well when using previous version of conda (4.9.2), but I had to update conda in some reasons ;(
So I tried reinstalling previous version of conda, but now the same error occurs. That means the version of conda doesn't matter.

Do you have any idea to solve this problem? or Can you explain what situation returns these messages?

Thanks,
Eum

**Comment by Psirving** [comment]
This is very likely an issue with your conda environment and not Superfold. From your conda environment, try recompiling RNAstructure and confirm that those executables are in your path before running Superfold.
