### ISSUE TITLE
IndexError in 'maxChar = len(str(lowSHAPEregions[-1][1]))'

### ISSUE THREAD

**Issue by eumhh** [Weeks-UNC/Superfold#9]
In some cases, I get an IndexError as below:
- example-results_TPP.map from shapemapper-2.1.3 >> Works well. No error.
- example-results_TPP.map from shapemapper-2.1.5 >> IndexError

---
starting Partition function calculation...
starting Fold...
drawing figures...
Traceback (most recent call last):
  File "/home/user/Superfold.py", line 1421, in <module>
    main()
  File "/home/user/Superfold.py", line 233, in main
    maxChar = len(str(lowSHAPEregions[-1][1]))
IndexError: list index out of range
---

.ct file was generated in both cases.
What could induce this error?
If I get this error, are there any considerations when interpreting the output?

Thanks,
Eum

**Comment by Psirving** [comment]
Could you send me the two .map files? My guess is that since TPP is so short, it has no low SHAPE regions. However, I'm not sure why the result would be different from shapemapper-2.1.3.
